version: '3'

networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "user"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '8G'